### ISSUE TITLE
bug(Community::Organizations::NoDefaultVPC): Resource NoDefaultVpc failed because Internal Failure

### ISSUE THREAD

**Issue by dannysteenman** [org-formation/aws-resource-providers#102]
We're using this community package: **Community::Organizations::NoDefaultVPC** and installed it using org-formation as explained in these instructions: https://github.com/org-formation/aws-resource-providers/blob/master/ec2/no-default-vpc/installation.md#installation-using-org-formation-task

Next to that, we've supplied a task to deploy the stack (stackname: compliance-config) using this example: https://github.com/org-formation/aws-resource-providers/blob/master/ec2/no-default-vpc/example.yml

So our tasks look like this:
```
Parameters:
  <<: !Include "../organization-parameters.yml"

#NoDefaultVPC
CommunityEc2NoDefaultVpcsRP:
  Type: register-type
  SchemaHandlerPackage: s3://community-resource-provider-catalog/community-organizations-nodefaultvpc-0.1.0.zip
  ResourceType: 'Community::Organizations::NoDefaultVPC'
  MaxConcurrentTasks: 10
  OrganizationBinding:
    IncludeMasterAccount: true
    Account: '*'
    Region: !Ref primaryRegion

ComplianceTemplate:
  Type: update-stacks
  Template: ./compliance-template.yml
  StackName: compliance-config
  StackDescription: Remediations for AWS Foundational Security Best Practices
  MaxConcurrentStacks: 10
  FailedStackTolerance: 10
  DefaultOrganizationBindingRegion: !Ref primaryRegion
  OrganizationBinding:
    IncludeMasterAccount: true
    Account: '*'
    Region: !Ref primaryRegion
``` 

However, the defaultvpc's are removed the first time. But running the pipeline again having this task enabled causes the following errors:

```
INFO: Executing: register-type CommunityEc2NoDefaultVpcsRP.
622 | DEBG: Setting build action on register-type / CommunityEc2NoDefaultVpcsRP for 012345678910/eu-west-1 to None - hash matches stored target. (012345678910 = Account1)
DEBG: Stack compliance-config in account 012345678910 (eu-west-1) update starting... (012345678910 = Account1)
645 | ERROR: error updating CloudFormation stack compliance-config in account 012345678910 (eu-west-1).
646 | Resource is not in the state stackCreateComplete (012345678910 = Account1)
647 | ERROR: Resource NoDefaultVpc failed because Internal Failure.
648 | ERROR: Stack compliance-config in account 012345678910 (eu-west-1) update failed. reason: Resource is not in the state stackCreateComplete (012345678910 = Account1)
649 | Resource is not in the state stackCreateComplete (use option --print-stack to print stack)
``` 

I would expect org-formation to skip making changes if it detects that there are no default vpc's anymore. Now, it's causing the pipeline to slow down since it retries the tasks before giving up. 

As a workaround, I've disabled the task.
