### ISSUE TITLE
Resource of type 'Community::Organizations::Policy' with identifier 'DenyLargeEC2Instances' already exists

### ISSUE THREAD

**Issue by NickDarvey** [org-formation/aws-resource-providers#103]
Despite #70, I've been unable to deploy my org-formation for a while. I've tried removing the SCP and redeploying, but I consistently get this error:

>ERROR: Resource Scp failed because Resource handler returned message: "Error: Resource of type 'Community::Organizations::Policy' with identifier 'DenyLargeEC2Instances' already exists." (RequestToken: asdf, HandlerErrorCode: AlreadyExists).
>ERROR: Stack example-deny-large-ec2 in account 1234 (us-east-1) update failed. reason: Resource is not in the state stackCreateComplete (1234= ManagementAccount)

Do I need to do something in my account so that the `delete_then_create` starts working?

### org-formation _task.yml

<details>

```yml
OrganizationsPolicyRp:
  Type: register-type
  ResourceType: 'Community::Organizations::Policy'
  SchemaHandlerPackage: !Sub 's3://${catalogBucket}/community-organizations-policy-0.2.2.zip'
  MaxConcurrentTasks: 100
  OrganizationBinding:
    IncludeMasterAccount: true
    Region: us-east-1 # Only compatible to us-east-1 region
```

</details>

### example-deny-large-ec2 template

<details>

```json

{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {},
  "Resources": {
    "Scp": {
      "Type": "Community::Organizations::Policy",
      "Properties": {
        "Name": "DenyLargeEC2Instances",
        "Description": "Deny running EC2 instances larger than 4xlarge",
        "PolicyType": "SERVICE_CONTROL_POLICY",
        "TargetIds": [
          "account1",
          "account2",
          "account3",
          "account4",
          "account5",
          "account6",
          "account7",
          "account8",
          "account9",
          "account10",
          "account11"
        ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "DenyLargerThan4XLarge",
              "Effect": "Deny",
              "Action": [
                "ec2:RunInstances"
              ],
              "Resource": "arn:aws:ec2:*:*:instance/*",
              "Condition": {
                "ForAnyValue:StringNotLike": {
                  "ec2:InstanceType": [
                    "*.nano",
                    "*.small",
                    "*.micro",
                    "*.medium",
                    "*.large",
                    "*.xlarge",
                    "*.2xlarge",
                    "*.4xlarge"
                  ]
                }
              }
            }
          ]
        }
      }
    }
  },
  "Outputs": {}
}
```

</details>
