### ISSUE TITLE
Community::EC2::NoDefaultVPC Resource

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/aws-resource-providers#19]
The Community::EC2::NoDefaultVpc resource can be used to remove the Default VPC.

``` yaml
Type: Community::EC2::NoDefaultVPC
Properties:
 DeleteDefaultVPC: true| false #default is true
```

If the resource is created or `DeleteDefaultVPC` is set to `true` the default VPC in the current region is deleted
If the resource is deleted or `DeleteDefaultVPC` is set to `false` a default VPC in the current region is created :-)

questions:
- should there be a `DeleteDefaultVPC` or can we do wihtout?
