### ISSUE TITLE
Community::SecurityHub::Hub, Master & Members

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/aws-resource-providers#27]
Community::SecurityHub::Hub is a better [AWS::SecurityHub::Hub](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-securityhub-hub.html)

Loosely modeled after GuardDuty::Master and GuardDuty::Member.

SecurityHub supports inviting multiple accounts at once, therefore Members (plural).
Master resource goes into the Mester accounts.
Member resource goes into the Master account.
This doesn't make complete sense for me, but it is how GuardDuty works...

``` yaml
  SecurityHubMembers:
    Type: Community::SecurityHub::Members
    Properties:
      MemberAccountIDs: List<String>
```

Community::SecurityHub::Members calls apis: 
- create-members
- invite-members

``` yaml
  SecurityHubMaster:
    Type: Community::SecurityHub::Master
    Properties:
      MasterAccountId: String
```
Community::SecurityHub::Master calls apis:
- list-invitations
- accept-invitation (compares on MasterAccountId)

``` yaml
  SecurityHub:
    Type: Community::SecurityHub::Hub
    Properties:
      AutoEnableControls: true | false # default true
      Standards: 
        EnablePCIDSS: true | false # default false
        EnableCISFoundations: true | false # default false
        EnableSecurityFoundations: true | false # default false
```
Community::SecurityHub::Hub. calls apis:
- update-security-hub-configuration
- enable-security-hub
