### ISSUE TITLE
AWS::IAM::OpenIDConnectProvider

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/aws-resource-providers#35]
The AWS::IAM::OpenIDConnectProvider allows users to set up a trust with an open id connect provider.

Proposal to do so using the following resource

``` yaml
Type: AWS::IAM::OpenIDConnectProvider
Properties: 
  Url: String # The URL of the identity provider
  ClientIds: List<String> # list of client ids/ audiences
  Thumprints: List<String> # list of certificate thumbprints
````
