### ISSUE TITLE
Community::CostExplorer::AnomalyMonitor

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/aws-resource-providers#36]
The Community::CostExplorer::AnomalyMonitor allows users to set up an anomaly monitor

Proposal to do so using the following resource
``` yaml
Type: Community::CostExplorer::AnomalyMonitor
Properties: 
  MonitorName: String # Name of the anomaly monitor
  MonitorType: String # DIMENSIONAL or CUSTOM
  MonitorDimension: String # SERVICE
  MonitorSpecification: any # contains expression as JSON or YAML
  DimensionalValueCount: number 

```
