### ISSUE TITLE
Community::ServiceQuotas::EC2

### ISSUE THREAD

**Issue by zaro0508** [org-formation/aws-resource-providers#71]
provider to set the custom Service Quota limits for EC2 resources. e.g: to increase the maximum number of instances per AZ and region.

**Comment by PatMyron** [comment]
Instead of re-implementing Service Quotas types for each quota, probably worth considering a generic type:

```yaml
Properties:
  ServiceCode:
  QuotaCode:
  DesiredValue:
```
